Repository githubschool/the-mandalorian, pull requests merged in 2019-11, with the labels that each got.

#21 mlouis5 changed caption to labtocat
  _posts/0000-01-06-mlouis5.md
Labels: enhancement

#13 Create branch an
  _posts/0000-01-22-arunnachimuthu.md
Labels: enhancement

#16 itzslinky7 Added caption to mad scientist
  _posts/0000-01-19-itzslinky7.md
Labels: enhancement, help wanted

#10 beardofedu changes their slide
  _posts/0000-01-27-beardofedu.md
Labels: enhancement

#17 Update 0000-01-14-rameen99.md
  _posts/0000-01-14-rameen99.md
Labels: help wanted

#20 updated caption
  _posts/0000-01-27-studentaws01.md
Labels: enhancement
